spring:
	profiles:
		active:
		

---
spring:
	application:
		name: microservicecloud-config-dev
	profiles:
		active: -dev

---
spring:
	application:
		name: microservicecloud-config-test
	profiles:
		active: -test
			